/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lib_b_complex_type_t {
    pub id: ::core::ffi::c_int,
    pub is_active: bool,
}
unsafe extern "C" {
    pub fn app_a_init_with_lib_b(b_data: *mut lib_b_complex_type_t);
}
