use mockall::automock;

#[cfg_attr(test, automock)]
pub(crate) mod ffi {
    use super::*;
/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    pub fn lib_b_do_something(data: *mut lib_b_complex_type_t);
}
}
pub use mock_ffi::*;
